export const personalInfo = {
  name: "Tirth Vaghela",
  title: "Full-Stack Developer",
  subtitle: "MSc IT Student @ GLS University",
  email: "vaghelatirth719@gmail.com",
  location: "Ahmedabad, Gujarat, India",
  github: "https://github.com/Tirthvaghela",
  linkedin: "https://www.linkedin.com/in/tirthvaghela/",
  summary:
    "Motivated MSc IT student (Semester 9) at GLS University with strong skills in full-stack web development. Experienced in building modern web applications using Python, Django, Next.js, React, and databases like MySQL and MongoDB. Passionate about developing scalable applications and continuously learning new technologies.",
};

export const skills = {
  "Programming Languages": ["Python", "JavaScript", "TypeScript", "SQL"],
  "Frontend": ["React", "Next.js", "HTML", "CSS", "Tailwind CSS", "Flutter"],
  "Backend": ["Django", "Flask", "Node.js", "FastAPI", "REST APIs"],
  "Databases": ["MySQL", "MongoDB", "SQLite"],
  "AI / ML": ["YOLOv4", "YOLOv8", "OpenCV", "DeepFace", "ArcFace"],
  "Tools": ["Git", "GitHub", "VS Code", "Vercel"],
};

export const experience = [
  {
    company: "Prodigy InfoTech",
    role: "Full-Stack Web Development Intern",
    type: "Remote",
    period: "Feb 2026 – Mar 2026",
    points: [
      "Task 1 — Built a production-ready enterprise authentication system using Django REST Framework and React with JWT, 2FA (TOTP), session management, audit logging, and role-based access control.",
      "Task 2 — Developed a full-featured MERN stack Employee Management System with JWT auth, profile picture upload, advanced search/filtering, CSV/PDF export, and a professional Electrox Design System UI.",
      "Task 3 — Created a PHP + MySQL e-commerce platform (Local Pantry) with product catalog, shopping cart, wishlist, order tracking, admin dashboard, and inventory analytics.",
      "Task 4 — Built Vois, a full-stack social media platform using React, FastAPI, and MongoDB with JWT auth, post/like/comment system, follow system, trending analytics, and responsive glassmorphism UI.",
    ],
  },
];

export const education = [
  {
    institution: "GLS University",
    degree: "Master of Science in Information Technology (MSc IT)",
    note: "Integrated Master's — Currently in Semester 9",
    period: "2025 – 2027",
    status: "Pursuing",
  },
  {
    institution: "GLS University",
    degree: "Bachelor of Science in Information Technology (BSc IT)",
    note: "Completed as part of IMSC IT integrated program",
    period: "2022 – 2025",
    status: "Completed",
    cgpa: "7.64",
    distinction: "First Class with Distinction",
    degreeFile: "/bsc(it)-degree.pdf",
  },
];

export const projects = [
  {
    id: 1,
    slug: "urban-signal",
    title: "Urban Signal",
    subtitle: "Intelligent Traffic Management System",
    tech: ["Next.js", "TypeScript", "Flask", "OpenCV", "YOLOv4", "MySQL"],
    description: "AI that reads traffic better than humans. Real-time camera feeds, dynamic signal timing, and emergency vehicle priority built from scratch.",
    points: ["Developed AI-powered traffic management system analyzing real-time camera feeds to optimize signal timing.", "Implemented vehicle detection and classification using YOLOv4 and OpenCV.", "Designed dynamic signal timing algorithm based on traffic density across multiple lanes.", "Integrated emergency vehicle detection to prioritize ambulance lanes automatically."],
    github: "https://github.com/Tirthvaghela/Urban_Signal",
    collaborator: { name: "Dhruv Sadrawala", linkedin: "https://www.linkedin.com/in/dhruv-sadrawala22/" },
    buildDays: 65,
    category: "AI / ML",
    color: "#6366f1",
    featured: true,
  },
  {
    id: 2,
    slug: "eventease",
    title: "EventEase",
    subtitle: "Event Management Platform",
    tech: ["Django", "Django REST Framework", "SQLite"],
    description: "Because college events deserve better than WhatsApp groups. Role-based access, RSVP tracking, and real-time capacity management.",
    points: ["Built a web-based event management system for colleges with admin and student roles.", "Implemented RSVP system with real-time capacity tracking and event status updates.", "Developed REST APIs and email notification system for event updates.", "Enabled role-based authentication and multi-college support."],
    github: "https://github.com/Tirthvaghela/EventEase",
    collaborator: { name: "Dhruv Sadrawala", linkedin: "https://www.linkedin.com/in/dhruv-sadrawala22/" },
    buildDays: 40,
    category: "Web",
    color: "#10b981",
    featured: true,
  },
  {
    id: 3,
    slug: "freshvault",
    title: "FreshVault",
    subtitle: "Local Pantry E-Commerce Platform",
    tech: ["PHP", "MySQL", "Tailwind CSS"],
    description: "A full e-commerce engine for local grocery businesses — product catalog, cart, wishlist, admin dashboard, and analytics. All from scratch.",
    points: ["Developed a full-featured e-commerce platform for local grocery businesses.", "Implemented product management, shopping cart, wishlist, and order tracking system.", "Built admin dashboard for inventory, orders, and analytics management.", "Designed responsive UI using Tailwind CSS."],
    github: "https://github.com/Tirthvaghela/FreshValut",
    buildDays: 25,
    category: "Web",
    color: "#f59e0b",
    featured: false,
  },
  {
    id: 4,
    slug: "vois",
    title: "Vois",
    subtitle: "Social Media Platform",
    tech: ["React", "FastAPI", "MongoDB", "JWT"],
    description: "A social media platform built entirely solo. Posts, likes, follows, trending analytics — and a glassmorphism UI that actually looks good.",
    points: ["Developed a full-stack social media platform with posts, likes, comments, and follow system.", "Implemented JWT-based authentication and secure password hashing.", "Built REST APIs for user management, feed generation, and analytics features.", "Designed responsive UI using React, Vite, and TailwindCSS."],
    github: "https://github.com/Tirthvaghela/Vois",
    buildDays: 32,
    category: "Full-Stack",
    color: "#ec4899",
    featured: true,
  },
  {
    id: 5,
    slug: "electrox-mobile",
    title: "Electrox-Mobile",
    subtitle: "Mobile Digital Voting Platform",
    tech: ["Flutter", "Node.js", "Express", "MongoDB", "JWT"],
    description: "Secure digital voting on mobile — 4 roles, full election lifecycle, audit logging, and real-time updates. Democracy in your pocket.",
    points: ["Developed a full-stack mobile voting application with role-based access (Admin, Organizer, Candidate, Voter).", "Built secure backend APIs using Node.js and Express with JWT authentication and MongoDB.", "Implemented election lifecycle management including vote casting, result tracking, and audit logging.", "Integrated email notifications, deep linking, and real-time updates for election activities."],
    github: "https://github.com/Tirthvaghela/Electrox-Mobile",
    collaborator: { name: "Dhruv Sadrawala", linkedin: "https://www.linkedin.com/in/dhruv-sadrawala22/" },
    buildDays: 45,
    category: "Mobile",
    color: "#3b82f6",
    featured: false,
  },
  {
    id: 6,
    slug: "rigs",
    title: "RIGS",
    subtitle: "Roadside Intelligent Governance System",
    tech: ["React", "Node.js", "MongoDB", "YOLOv8", "OpenCV"],
    description: "YOLOv8 spots helmetless riders, OCR reads the plate, and the challan goes out automatically. No human needed in the loop.",
    points: ["Developed an AI-based system for helmet detection and automated e-challan generation.", "Integrated YOLOv8 and OCR for license plate recognition and violation detection.", "Built real-time dashboard for monitoring traffic violations and analytics.", "Implemented automated email system for sending challans to vehicle owners."],
    github: "https://github.com/Tirthvaghela/RIGS",
    collaborator: { name: "Dhruv Sadrawala", linkedin: "https://www.linkedin.com/in/dhruv-sadrawala22/" },
    buildDays: 22,
    category: "AI / ML",
    color: "#ef4444",
    featured: true,
  },
  {
    id: 7,
    slug: "wedding-face-finder",
    title: "Wedding Face Finder",
    subtitle: "AI Photo Search System",
    tech: ["Flask", "DeepFace", "ArcFace", "RetinaFace"],
    description: "Upload your face, find yourself in thousands of wedding photos. DeepFace + ArcFace doing what humans can't.",
    points: ["Developed AI-powered face recognition system to find users in photo collections.", "Implemented face detection and similarity matching using DeepFace and ArcFace.", "Built webcam capture interface and automated photo matching pipeline.", "Enabled batch download and adaptive matching for accurate results."],
    github: "https://github.com/Tirthvaghela/Wedding-Face-Finder",
    collaborator: { name: "Dhruv Sadrawala", linkedin: "https://www.linkedin.com/in/dhruv-sadrawala22/" },
    buildDays: 14,
    category: "AI / ML",
    color: "#8b5cf6",
    featured: false,
  },
  {
    id: 8,
    slug: "electrox-web",
    title: "Electrox Web",
    subtitle: "Secure Digital Voting Platform",
    tech: ["React", "Flask", "MongoDB", "JWT"],
    description: "Role-based voting system with bcrypt, JWT, audit logs, and analytics. Secure enough for real elections.",
    points: ["Built a secure role-based online voting system with Admin, Organizer, Candidate, and Voter roles.", "Implemented JWT authentication and bcrypt password hashing for security.", "Developed election creation, vote casting, and result analytics features.", "Integrated email notifications and audit logging system."],
    github: "https://github.com/Tirthvaghela/Electrox",
    collaborator: { name: "Dhruv Sadrawala", linkedin: "https://www.linkedin.com/in/dhruv-sadrawala22/" },
    buildDays: 38,
    category: "Full-Stack",
    color: "#06b6d4",
    featured: false,
  },
  {
    id: 9,
    slug: "gls-uni-portal",
    title: "GLS University Student Portal",
    subtitle: "Mobile-First Student Portal",
    tech: ["HTML", "JavaScript", "Tailwind CSS", "Vite"],
    description: "Because checking your results shouldn't feel like a chore. Ten pages, one navy-and-gold design system, and a digital ID card that actually tilts when you hover it.",
    points: [
      "Designed a complete 10-page portal — login, dashboard, attendance, fees, results, schedule, events, and a digital ID — under a custom navy/gold \"Academic Vanguard\" design system with its own type scale and icon set.",
      "Built a tabbed Schedule page: a weekly Class Schedule with a Mon–Sat day picker that auto-selects today, and an Exam Schedule with paper details and instructions.",
      "Created an interactive Digital Student ID card (tilt-on-hover) showing linked service status, a recent access log, and share/download/report-lost actions.",
      "Built a categorized FAQ support chatbot (Admissions, Fees, Academics, Campus) backed by a real CSV knowledge base of question-answer pairs.",
    ],
    github: "https://github.com/Tirthvaghela/GlsUni_mob_prototype",
    demo: "https://gls-uni-mob-prototype.vercel.app",
    category: "Web",
    color: "#14b8a6",
    featured: false,
  },
];

export const upcomingProject = {
  title: "VoiceForm AI",
  subtitle: "Multilingual Voice-to-Form Accessibility Engine",
  description:
    "Point your camera at any paper form. VoiceForm reads its exact layout, holds a real voice conversation with you in Gujarati, Hindi, or English, and hands back a print-ready PDF filled in perfectly — no typing, no OCR guesswork.",
  teasers: [
    "Understands arbitrary form layouts — not OCR guesswork, actual document structure.",
    "Holds a real multilingual voice conversation to collect every answer, field by field.",
    "Writes responses back onto the original PDF — pixel-perfect, box by box, font-matched.",
  ],
  tech: ["FastAPI", "PaddleOCR", "Whisper", "Gemini", "MongoDB", "Next.js"],
  category: "AI / ML",
  status: "Coming Soon",
  teaserLine: "You talk. It listens. And then...",
};
